### ISSUE TITLE
fix panic

### ISSUE THREAD

**Issue by shogo82148** [shogo82148/ssm-sign-proxy#1]
```
019/01/29 22:24:57 http: panic serving [::1]:52331: invalid WriteHeader code 0
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc000098f00)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1746 +0xd0
panic(0x13ad020, 0xc0004318b0)
        /usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
net/http.checkWriteHeaderCode(0x0)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1092 +0xe9
net/http.(*response).WriteHeader(0xc0001ce0e0, 0x0)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1105 +0x63
github.com/shogo82148/ssm-sign-proxy.(*Response).WriteTo(0xc000056280, 0x1500880, 0xc0001ce0e0, 0x0, 0x0)
        /Users/shogoichinose/src/github.com/shogo82148/ssm-sign-proxy/request.go:192 +0x249
github.com/shogo82148/ssm-sign-proxy.(*Proxy).ServeHTTP(0xc00017a200, 0x1500880, 0xc0001ce0e0, 0xc0001d4000)
        /Users/shogoichinose/src/github.com/shogo82148/ssm-sign-proxy/proxy.go:101 +0x27c
net/http.serverHandler.ServeHTTP(0xc000175520, 0x1500880, 0xc0001ce0e0, 0xc0001d4000)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000098f00, 0x1500bc0, 0xc000084540)
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2851 +0x2f5
```

**Comment by shogo82148** [comment]
fixed bt https://github.com/shogo82148/ssm-sign-proxy/commit/273d240fe94501f6a063a0e35157c143704dd1c4
